source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'jumbyButtonPod_Example', :exclusive => true do
  pod 'jumbyButtonPod', :path => '../'
end

target 'jumbyButtonPod_Tests', :exclusive => true do
  pod 'jumbyButtonPod', :path => '../'

  
end
